version: "3"
services:
  db:
    image: bitnami/postgresql
    container_name: api-solid-pg
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid
    ports:
      - "5432:5432"
